# === docker-compose.yml ===
version: '3.9'

services:
  web:
    build: .
    command: gunicorn airbnb_clone.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: airbnb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A airbnb_clone worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/code

volumes:
  postgres_data:
